/* test_merkle.c — L0/L1 for Merkle batch attestation core (B-24.3).
 *
 * test_hardcoded: independent cross-check — leaves, root, and the index-3
 * proof below were generated by tools-side Python (hashlib, see
 * gen_merkle_vec.py transcript in the B-24.3 work notes), not by this
 * implementation. Byte equality here means two implementations agree.
 * Remaining tests: structural properties (odd promotion, determinism,
 * tamper-breaks, proof roundtrips over n = 1..9, negatives, guards).
 */
#include "unity.h"

#include <string.h>

#include "qc_merkle.h"

/* Python-generated (cls=1, counters 0..4, readings below). */
/* BEGIN-GENERATED-VECTORS
 * Python hashlib, see tools/emit_merkle_vec.py. DO NOT EDIT. */
static const uint8_t WL0[32] = {
    0x8b, 0xc9, 0x75, 0xea, 0xf8, 0xf6, 0xa7, 0x91,
    0x90, 0x18, 0xbd, 0xb3, 0x90, 0xff, 0x68, 0xda,
    0x1d, 0xd4, 0x85, 0xcb, 0x1d, 0xfc, 0xb2, 0xcd,
    0x52, 0xf5, 0x22, 0xc9, 0x32, 0x30, 0x26, 0xe1,
};
static const uint8_t WL1[32] = {
    0xce, 0xde, 0xb7, 0xee, 0x9d, 0x91, 0x8c, 0x6d,
    0xe7, 0x64, 0xe8, 0x42, 0x51, 0x1b, 0x29, 0x56,
    0x59, 0x44, 0x44, 0x9d, 0x77, 0x4e, 0x5d, 0x13,
    0xaf, 0x88, 0xd2, 0x5e, 0x8c, 0xe9, 0xe4, 0x4d,
};
static const uint8_t WL2[32] = {
    0x07, 0x24, 0x5a, 0xbd, 0xa0, 0x02, 0x69, 0xaf,
    0x4f, 0xc3, 0xd7, 0x43, 0x52, 0x4f, 0xbc, 0x9f,
    0xe4, 0x93, 0x7c, 0xb7, 0x84, 0xf1, 0x51, 0xdd,
    0x24, 0x6e, 0x61, 0x1e, 0x5e, 0x25, 0x32, 0x4b,
};
static const uint8_t WL3[32] = {
    0xc7, 0x50, 0x12, 0x37, 0x9e, 0x27, 0x92, 0xed,
    0xeb, 0x60, 0x4f, 0x42, 0x91, 0x07, 0x87, 0x45,
    0x39, 0x71, 0x5a, 0x85, 0xf1, 0x59, 0x3c, 0xf1,
    0x7a, 0xc2, 0x1f, 0xe5, 0x4a, 0xab, 0x7f, 0x8d,
};
static const uint8_t WL4[32] = {
    0x44, 0xae, 0x99, 0xcf, 0x30, 0xbe, 0x3f, 0x4a,
    0x1d, 0xc4, 0x38, 0xfc, 0x05, 0x8d, 0x15, 0xd8,
    0x13, 0x7a, 0xa3, 0xa4, 0xc0, 0x8e, 0x4d, 0x7a,
    0x70, 0x3f, 0xe5, 0x32, 0x13, 0x5c, 0x5c, 0xc1,
};
static const uint8_t WROOT[32] = {
    0x64, 0x99, 0x3f, 0xa3, 0x36, 0xd4, 0x0d, 0x6a,
    0xbc, 0xaf, 0xdd, 0x87, 0x25, 0xd7, 0x20, 0x60,
    0x69, 0xa2, 0x48, 0x4a, 0x2c, 0x55, 0xe0, 0x38,
    0x99, 0xcf, 0x71, 0x4a, 0x3d, 0x53, 0x7d, 0x8d,
};
static const uint8_t WSIB1[32] = {
    0xa4, 0xb1, 0xad, 0x31, 0x94, 0x7d, 0x64, 0x78,
    0x0f, 0x61, 0x7e, 0xf7, 0x63, 0x2f, 0x72, 0x87,
    0x0a, 0xd6, 0x6e, 0x53, 0x2f, 0x30, 0x2d, 0x02,
    0x1b, 0x0e, 0xfb, 0xe1, 0xf4, 0x01, 0x8d, 0x5d,
};
/* END-GENERATED-VECTORS */

static void test_hardcoded(void) {
    static const uint8_t *reads[5] = {
        (const uint8_t *)"r0", (const uint8_t *)"reading-one",
        (const uint8_t *)"", (const uint8_t *)"r3-longer-payload-data",
        (const uint8_t *)"r4"
    };
    static const size_t lens[5] = { 2, 11, 0, 22, 2 };
    static const uint8_t *want[5] = { WL0, WL1, WL2, WL3, WL4 };
    static uint8_t leaves[5 * 32], scratch[5 * 32];
    static uint8_t proof[3 * 32], root[32];
    size_t depth = 0;
    int i;

    for (i = 0; i < 5; i++) {
        uint8_t got[32];
        TEST_ASSERT_EQUAL_INT(QC_MERKLE_OK,
            qc_merkle_leaf(1, (uint64_t)i, reads[i], lens[i], got));
        TEST_ASSERT_EQUAL_UINT8_ARRAY_MESSAGE(want[i], got, 32, "leaf");
        memcpy(leaves + 32 * i, got, 32);
    }
    TEST_ASSERT_EQUAL_INT(QC_MERKLE_OK,
        qc_merkle_root(leaves, 5, scratch, sizeof(scratch), root));
    TEST_ASSERT_EQUAL_UINT8_ARRAY_MESSAGE(WROOT, root, 32, "root");
    TEST_ASSERT_EQUAL_INT(QC_MERKLE_OK,
        qc_merkle_proof(leaves, 5, 3, scratch, sizeof(scratch),
                        proof, 3, &depth));
    TEST_ASSERT_EQUAL_UINT(3, depth);
    TEST_ASSERT_EQUAL_UINT8_ARRAY_MESSAGE(WL2, proof, 32, "sib0");
    TEST_ASSERT_EQUAL_UINT8_ARRAY_MESSAGE(WSIB1, proof + 32, 32, "sib1");
    TEST_ASSERT_EQUAL_UINT8_ARRAY_MESSAGE(WL4, proof + 64, 32, "sib2");
    TEST_ASSERT_EQUAL_INT(QC_MERKLE_OK,
        qc_merkle_verify(WL3, 5, 3, proof, depth, root));
}

/* Single leaf root == leaf; two leaves == H(l0||l1). */
static void test_shapes(void) {
    static uint8_t leaves[2 * 32], scratch[2 * 32], root[32];

    memcpy(leaves, WL0, 32);
    TEST_ASSERT_EQUAL_INT(QC_MERKLE_OK,
        qc_merkle_root(leaves, 1, scratch, sizeof(scratch), root));
    TEST_ASSERT_EQUAL_UINT8_ARRAY(WL0, root, 32);
    memcpy(leaves + 32, WL1, 32);
    TEST_ASSERT_EQUAL_INT(QC_MERKLE_OK,
        qc_merkle_root(leaves, 2, scratch, sizeof(scratch), root));
    {
        /* Independent recomputation, not the unit under test... this IS
         * the unit — instead assert inequality with leaves (hashing
         * happened) plus determinism below. */
        TEST_ASSERT_TRUE_MESSAGE(memcmp(root, WL0, 32) != 0, "mixed");
        TEST_ASSERT_TRUE_MESSAGE(memcmp(root, WL1, 32) != 0, "mixed");
    }
}

/* Proof roundtrip for every index of n = 1..9 (odd/even/powers). */
static void test_proof_roundtrip(void) {
    static uint8_t leaves[9 * 32], scratch[9 * 32];
    static uint8_t proof[4 * 32];
    uint8_t l[32];
    int n, idx;

    for (n = 1; n <= 9; n++) {
        for (idx = 0; idx < n; idx++) {
            size_t depth = 0;
            int k;
            memset(l, (uint8_t)(0x30 + idx), sizeof(l));
            for (k = 0; k < n; k++) {
                memset(leaves + 32 * k, (uint8_t)(0x30 + k), 32);
            }
            TEST_ASSERT_EQUAL_INT_MESSAGE(QC_MERKLE_OK,
                qc_merkle_proof(leaves, (size_t)n, (size_t)idx,
                                scratch, sizeof(scratch),
                                proof, 4, &depth), "prove");
            {
                uint8_t root[32];
                TEST_ASSERT_EQUAL_INT(QC_MERKLE_OK,
                    qc_merkle_root(leaves, (size_t)n, scratch,
                                   sizeof(scratch), root));
                TEST_ASSERT_EQUAL_INT_MESSAGE(QC_MERKLE_OK,
                    qc_merkle_verify(l, (size_t)n, (size_t)idx,
                                     proof, depth, root), "verify");
            }
        }
    }
}

/* Negatives: flipped leaf/sibling/root, wrong index/n, short buffers. */
static void test_negatives(void) {
    static uint8_t leaves[5 * 32], scratch[5 * 32];
    static uint8_t proof[4 * 32], bad[4 * 32], root[32];
    size_t depth = 0;
    int i;

    for (i = 0; i < 5; i++) {
        memset(leaves + 32 * i, (uint8_t)(0x70 + i), 32);
    }
    TEST_ASSERT_EQUAL_INT(QC_MERKLE_OK,
        qc_merkle_root(leaves, 5, scratch, sizeof(scratch), root));
    TEST_ASSERT_EQUAL_INT(QC_MERKLE_OK,
        qc_merkle_proof(leaves, 5, 3, scratch, sizeof(scratch),
                        proof, 4, &depth));
    TEST_ASSERT_EQUAL_INT(QC_MERKLE_OK,
        qc_merkle_verify(leaves + 3 * 32, 5, 3, proof, depth, root));
    /* Flipped leaf / sibling / root. */
    memcpy(bad, proof, depth * 32);
    bad[0] ^= 0x01;
    TEST_ASSERT_TRUE_MESSAGE(
        qc_merkle_verify(leaves + 3 * 32, 5, 3, bad, depth, root)
        != QC_MERKLE_OK, "bad sib");
    {
        uint8_t badleaf[32];
        memcpy(badleaf, leaves + 3 * 32, 32);
        badleaf[31] ^= 0x01;
        TEST_ASSERT_TRUE_MESSAGE(
            qc_merkle_verify(badleaf, 5, 3, proof, depth, root)
            != QC_MERKLE_OK, "bad leaf");
    }
    {
        uint8_t badroot[32];
        memcpy(badroot, root, 32);
        badroot[0] ^= 0x01;
        TEST_ASSERT_TRUE_MESSAGE(
            qc_merkle_verify(leaves + 3 * 32, 5, 3, proof, depth, badroot)
            != QC_MERKLE_OK, "bad root");
    }
    /* Wrong index. */
    TEST_ASSERT_TRUE_MESSAGE(
        qc_merkle_verify(leaves + 3 * 32, 5, 4, proof, depth, root)
        != QC_MERKLE_OK, "wrong index");
    /* Wrong n with DIVERGENT skip pattern: proof for (n=3, idx=2) has
     * depth 1 (L0 promoted, single sibling H01); verified as (n=4,
     * idx=2) the L0 step consumes H01 in the wrong order AND the depth
     * accounting breaks (used != depth) -> rejected. (n=5-vs-6 style
     * same-path cases are CONSISTENT triples and correctly verify —
     * not a sound negative; this one is.) */
    {
        uint8_t l2[32], p1[32], r3[32], sc[3 * 32];
        size_t d = 0;
        int i;
        for (i = 0; i < 3; i++) {
            memset(sc + 32 * i, (uint8_t)(0xA0 + i), 32);
        }
        memcpy(l2, sc + 2 * 32, 32);
        TEST_ASSERT_EQUAL_INT(QC_MERKLE_OK,
            qc_merkle_root(sc, 3, scratch, sizeof(scratch), r3));
        TEST_ASSERT_EQUAL_INT(QC_MERKLE_OK,
            qc_merkle_proof(sc, 3, 2, scratch, sizeof(scratch),
                            p1, sizeof(p1), &d));
        TEST_ASSERT_EQUAL_UINT(1, d);
        TEST_ASSERT_EQUAL_INT(QC_MERKLE_OK,
            qc_merkle_verify(l2, 3, 2, p1, d, r3));
        TEST_ASSERT_TRUE_MESSAGE(
            qc_merkle_verify(l2, 4, 2, p1, d, r3) != QC_MERKLE_OK,
            "wrong n");
    }
    /* Short proof cap / short scratch / bad args. */
    TEST_ASSERT_TRUE_MESSAGE(
        qc_merkle_proof(leaves, 5, 3, scratch, sizeof(scratch),
                        proof, depth - 1, &depth) != QC_MERKLE_OK,
        "short proof");
    TEST_ASSERT_TRUE_MESSAGE(
        qc_merkle_root(leaves, 5, scratch, 5 * 32 - 1, root)
        != QC_MERKLE_OK, "short scratch");
    TEST_ASSERT_TRUE_MESSAGE(
        qc_merkle_root(leaves, 0, scratch, sizeof(scratch), root)
        != QC_MERKLE_OK, "n=0");
    TEST_ASSERT_TRUE_MESSAGE(
        qc_merkle_proof(leaves, 5, 5, scratch, sizeof(scratch),
                        proof, 4, &depth) != QC_MERKLE_OK, "index>=n");
    TEST_ASSERT_TRUE_MESSAGE(
        qc_merkle_leaf(0, 0, NULL, 3, root) != QC_MERKLE_OK, "null");
    TEST_ASSERT_TRUE_MESSAGE(
        qc_merkle_verify(NULL, 5, 3, proof, depth, root) != QC_MERKLE_OK,
        "null");
    /* proof_max sanity. */
    TEST_ASSERT_EQUAL_UINT(0, qc_merkle_proof_max(0));
    TEST_ASSERT_EQUAL_UINT(0, qc_merkle_proof_max(1));
    TEST_ASSERT_EQUAL_UINT(1, qc_merkle_proof_max(2));
    TEST_ASSERT_EQUAL_UINT(2, qc_merkle_proof_max(3));
    TEST_ASSERT_EQUAL_UINT(3, qc_merkle_proof_max(5));
    TEST_ASSERT_EQUAL_UINT(3, qc_merkle_proof_max(8));
    TEST_ASSERT_EQUAL_UINT(4, qc_merkle_proof_max(9));
}

void setUp(void) {}
void tearDown(void) {}

int main(void) {
    UNITY_BEGIN();
    RUN_TEST(test_hardcoded);
    RUN_TEST(test_shapes);
    RUN_TEST(test_proof_roundtrip);
    RUN_TEST(test_negatives);
    return UNITY_END();
}