/* test_xcheck.c — independent cross-check (B-10.3/B-11.3, B-02.3 gate).
 *
 * Vectors: tests/c/wycheproof_xcheck.h, generated by
 * tools/wycheproof_to_c.py from the C2SP Wycheproof corpus (implementations
 * independent of mlkem-native/mldsa-native). Every vector is exercised
 * through the SAME adapter entry points as production code — no backend
 * symbols are touched directly.
 *
 * Assumptions under test (failures here mean assumption OR backend wrong;
 * investigate, never silently adjust):
 * - KEM keygen_seed: seed(64) -> (ek, dk) via keypair_derand.
 * - KEM encaps valid: enc_derand(ek, m32) -> (c, K).
 * - KEM encaps invalid (full-length malformed ek): BAD_KEY.
 * - DSA keygen: keypair(seed32).pk == group publicKey.
 * - DSA verify vectors were generated with EMPTY context: verify runs
 *   with ctx NULL/len 0. A systematic valid-vector failure here would
 *   mean nonzero ctx — investigate before touching the driver.
 */
#include "unity.h"

#include <stdio.h>
#include <string.h>

#include "qc_dsa.h"
#include "qc_kem.h"
#include "wycheproof_xcheck.h"

static size_t hex_decode(const char *hex, uint8_t *out, size_t cap) {
    /* Odd-length hex would silently drop a trailing nibble — fail closed. */
    TEST_ASSERT_TRUE_MESSAGE(strlen(hex) % 2 == 0, "odd hex");
    size_t n = strlen(hex) / 2;
    TEST_ASSERT_TRUE_MESSAGE(n <= cap, "hex overflow");
    for (size_t i = 0; i < n; i++) {
        unsigned v;
        TEST_ASSERT_EQUAL_INT_MESSAGE(1, sscanf(hex + 2 * i, "%2x", &v),
                                      "bad hex");
        out[i] = (uint8_t)v;
    }
    return n;
}

/* ---------------- KEM ---------------- */

#define RUN_KEM_KEYGEN(lvl, tab)                                         \
    static void test_wy_kem_keygen_##lvl(void) {                          \
        static uint8_t seed[64], pk[1568], sk[3168], e[1568], d[3168];    \
        for (size_t i = 0; i < tab##_n; i++) {                            \
            hex_decode(tab[i].seed, seed, sizeof(seed));                  \
            hex_decode(tab[i].ek, e, sizeof(e));                           \
            hex_decode(tab[i].dk, d, sizeof(d));                           \
            TEST_ASSERT_EQUAL_INT_MESSAGE(QC_KEM_OK,                       \
                qc_kem_keypair(QC_KEM_##lvl, pk, sk, seed), #lvl);         \
            TEST_ASSERT_EQUAL_UINT8_ARRAY_MESSAGE(e, pk,                   \
                qc_kem_pk_bytes(QC_KEM_##lvl), #lvl);                      \
            TEST_ASSERT_EQUAL_UINT8_ARRAY_MESSAGE(d, sk,                   \
                qc_kem_sk_bytes(QC_KEM_##lvl), #lvl);                      \
        }                                                                 \
    }

RUN_KEM_KEYGEN(512, wy_kem_keygen_512)
RUN_KEM_KEYGEN(768, wy_kem_keygen_768)
RUN_KEM_KEYGEN(1024, wy_kem_keygen_1024)

#define RUN_KEM_ENC(lvl, tab, bad)                                       \
    static void test_wy_kem_enc_##lvl(void) {                             \
        static uint8_t ek[1568], m[32], c[1568], k[32];                   \
        static uint8_t ct[1568], ss[32];                                  \
        for (size_t i = 0; i < tab##_n; i++) {                            \
            hex_decode(tab[i].ek, ek, sizeof(ek));                        \
            hex_decode(tab[i].m, m, sizeof(m));                            \
            hex_decode(tab[i].c, c, sizeof(c));                            \
            hex_decode(tab[i].k, k, sizeof(k));                            \
            TEST_ASSERT_EQUAL_INT_MESSAGE(QC_KEM_OK,                       \
                qc_kem_encaps(QC_KEM_##lvl, ct, ss, ek, m), #lvl);         \
            TEST_ASSERT_EQUAL_UINT8_ARRAY_MESSAGE(c, ct,                   \
                qc_kem_ct_bytes(QC_KEM_##lvl), #lvl);                      \
            TEST_ASSERT_EQUAL_UINT8_ARRAY_MESSAGE(k, ss, 32, #lvl);        \
        }                                                                 \
        for (size_t i = 0; i < bad##_n; i++) {                             \
            hex_decode(bad[i].ek, ek, sizeof(ek));                        \
            memset(m, 0x5A, sizeof(m));                                    \
            TEST_ASSERT_EQUAL_INT_MESSAGE(QC_KEM_BAD_KEY,                   \
                qc_kem_encaps(QC_KEM_##lvl, ct, ss, ek, m), #lvl);         \
        }                                                                 \
    }

RUN_KEM_ENC(512, wy_kem_enc_512, wy_kem_bad_512)
RUN_KEM_ENC(768, wy_kem_enc_768, wy_kem_bad_768)
RUN_KEM_ENC(1024, wy_kem_enc_1024, wy_kem_bad_1024)

/* ---------------- DSA ---------------- */

#define RUN_DSA_KEYGEN(lvl, tab)                                         \
    static void test_wy_dsa_keygen_##lvl(void) {                          \
        static uint8_t seed[32], pk[2592], sk[4896], e[2592];             \
        for (size_t i = 0; i < tab##_n; i++) {                            \
            hex_decode(tab[i].seed, seed, sizeof(seed));                  \
            hex_decode(tab[i].pk, e, sizeof(e));                           \
            TEST_ASSERT_EQUAL_INT_MESSAGE(QC_DSA_OK,                       \
                qc_dsa_keypair(QC_DSA_##lvl, pk, sk, seed), #lvl);         \
            TEST_ASSERT_EQUAL_UINT8_ARRAY_MESSAGE(e, pk,                   \
                qc_dsa_pk_bytes(QC_DSA_##lvl), #lvl);                      \
        }                                                                 \
    }

RUN_DSA_KEYGEN(44, wy_dsa_keygen_44)
RUN_DSA_KEYGEN(65, wy_dsa_keygen_65)
RUN_DSA_KEYGEN(87, wy_dsa_keygen_87)

#define RUN_DSA_VERIFY(lvl, tab)                                         \
    static void test_wy_dsa_verify_##lvl(void) {                          \
        static uint8_t pk[2592], msg[512], sig[4627], ctx[256];           \
        size_t npk = qc_dsa_pk_bytes(QC_DSA_##lvl);                       \
        size_t nsig = qc_dsa_sig_bytes(QC_DSA_##lvl);                     \
        for (size_t i = 0; i < tab##_n; i++) {                            \
            size_t mlen, clen;                                            \
            int want, rc;                                                 \
            /* Converter guarantees same-shape vectors; pin it here. */  \
            TEST_ASSERT_EQUAL_UINT_MESSAGE(npk,                           \
                hex_decode(tab[i].pk, pk, sizeof(pk)), #lvl);             \
            mlen = hex_decode(tab[i].msg, msg, sizeof(msg));              \
            TEST_ASSERT_EQUAL_UINT_MESSAGE(nsig,                           \
                hex_decode(tab[i].sig, sig, sizeof(sig)), #lvl);          \
            clen = hex_decode(tab[i].ctx, ctx, sizeof(ctx));              \
            TEST_ASSERT_TRUE_MESSAGE(clen <= 256, #lvl);                  \
            want = tab[i].expect;                                         \
            rc = qc_dsa_verify(QC_DSA_##lvl, mlen > 0 ? msg : NULL, mlen, \
                               clen > 0 ? ctx : NULL, clen, sig, pk);     \
            if (want != rc) {                                             \
                printf("xcheck %s[%zu] want=%d got=%d\n",                  \
                       #lvl, i, want, rc);                                \
            }                                                             \
            TEST_ASSERT_EQUAL_INT_MESSAGE(want, rc, #lvl);                \
        }                                                                 \
    }

RUN_DSA_VERIFY(44, wy_dsa_verify_44)
RUN_DSA_VERIFY(65, wy_dsa_verify_65)
RUN_DSA_VERIFY(87, wy_dsa_verify_87)

void setUp(void) {}
void tearDown(void) {}

/* An empty table loops zero times and passes vacuously. A generator
 * regression emitting [] must fail loudly instead. */
static void test_tables_nonempty(void) {
    TEST_ASSERT_TRUE(wy_kem_keygen_512_n > 0);
    TEST_ASSERT_TRUE(wy_kem_keygen_768_n > 0);
    TEST_ASSERT_TRUE(wy_kem_keygen_1024_n > 0);
    TEST_ASSERT_TRUE(wy_kem_enc_512_n > 0);
    TEST_ASSERT_TRUE(wy_kem_enc_768_n > 0);
    TEST_ASSERT_TRUE(wy_kem_enc_1024_n > 0);
    TEST_ASSERT_TRUE(wy_kem_bad_512_n > 0);
    TEST_ASSERT_TRUE(wy_kem_bad_768_n > 0);
    TEST_ASSERT_TRUE(wy_kem_bad_1024_n > 0);
    TEST_ASSERT_TRUE(wy_dsa_keygen_44_n > 0);
    TEST_ASSERT_TRUE(wy_dsa_keygen_65_n > 0);
    TEST_ASSERT_TRUE(wy_dsa_keygen_87_n > 0);
    TEST_ASSERT_TRUE(wy_dsa_verify_44_n > 0);
    TEST_ASSERT_TRUE(wy_dsa_verify_65_n > 0);
    TEST_ASSERT_TRUE(wy_dsa_verify_87_n > 0);
}

int main(void) {
    UNITY_BEGIN();
    RUN_TEST(test_tables_nonempty);
    RUN_TEST(test_wy_kem_keygen_512);
    RUN_TEST(test_wy_kem_keygen_768);
    RUN_TEST(test_wy_kem_keygen_1024);
    RUN_TEST(test_wy_kem_enc_512);
    RUN_TEST(test_wy_kem_enc_768);
    RUN_TEST(test_wy_kem_enc_1024);
    RUN_TEST(test_wy_dsa_keygen_44);
    RUN_TEST(test_wy_dsa_keygen_65);
    RUN_TEST(test_wy_dsa_keygen_87);
    RUN_TEST(test_wy_dsa_verify_44);
    RUN_TEST(test_wy_dsa_verify_65);
    RUN_TEST(test_wy_dsa_verify_87);
    return UNITY_END();
}