/* test_aead.c — L0/L1 for the AES-256-GCM adapter (B-23 / F4).
 *
 * Two independent vector sources, deliberately kept separate:
 *
 * 1. test_cavp_*(): official NIST CAVP vectors from gcmEncryptExtIV256.rsp
 *    (AES-256, IVlen=96, Taglen=128), transcribed from
 *    quiche/quic/core/crypto/aes_256_gcm_encrypter_test.cc. Transcription
 *    confirmed by tools/verify_cavp.py, which re-derives every vector with
 *    Python `cryptography` (a separate implementation) byte-for-byte.
 *    Covers: empty PT, AAD-only, 128-bit PT, 408-bit PT with 160-bit AAD
 *    (multi-block, partial final block), 104-bit PT.
 *
 * 2. test_vector_*(): cross-implementation agreement against vectors
 *    generated by Python `cryptography` at authoring time. These are NOT
 *    CAVP vectors; they exist to catch regressions in the our-own
 *    key/nonce patterns used elsewhere in the codebase.
 */
#include "unity.h"

#include <stdio.h>
#include <string.h>

#include "qc_aead.h"

static void fill_key_nonce(uint8_t key[32], uint8_t nonce[12]) {
    for (int i = 0; i < 32; i++) {
        key[i] = (uint8_t)i;
    }
    for (int i = 0; i < 12; i++) {
        nonce[i] = (uint8_t)(0xA0 + i);
    }
}

static void expect_hex_n(const char *label, const uint8_t *got, size_t n,
                         const char *want_hex) {
    char buf[257];
    static const char hd[] = "0123456789abcdef";
    /* Unity rejects zero-length compares; empty ciphertext is a real case
     * (CAVP empty-PT vectors), so assert the expected shape instead. */
    if (n == 0) {
        TEST_ASSERT_EQUAL_STRING_MESSAGE("", want_hex, label);
        return;
    }
    for (size_t i = 0; i < n; i++) {
        buf[2 * i] = hd[(got[i] >> 4) & 0xF];
        buf[2 * i + 1] = hd[got[i] & 0xF];
    }
    buf[2 * n] = '\0';
    TEST_ASSERT_EQUAL_STRING_MESSAGE(want_hex, buf, label);
}

/* Decode lowercase hex into out; caller guarantees out is large enough.
 * TEST only — never on secret data. */
static size_t hex_decode(const char *hex, uint8_t *out, size_t out_cap) {
    size_t n = strlen(hex) / 2;
    TEST_ASSERT_TRUE_MESSAGE(n <= out_cap, "hex longer than buffer");
    for (size_t i = 0; i < n; i++) {
        unsigned v;
        TEST_ASSERT_EQUAL_INT_MESSAGE(1, sscanf(hex + 2 * i, "%2x", &v),
                                      "bad hex");
        out[i] = (uint8_t)v;
    }
    return n;
}

/* One CAVP vector: encrypt must reproduce the NIST CT and tag; decrypt
 * of the NIST CT with the NIST tag must recover the PT. Both directions
 * use the published constants — never our own output as the oracle. */
static void run_cavp(const char *label,
                     const char *key_hex, const char *iv_hex,
                     const char *pt_hex, const char *aad_hex,
                     const char *ct_hex, const char *tag_hex) {
    uint8_t key[32], iv[12];
    uint8_t pt[64], aad[32], ct[64], tag[16], back[64];
    uint8_t nist_ct[64], nist_tag[16];
    size_t pt_len, aad_len, nist_ct_len;
    int rc;

    hex_decode(key_hex, key, sizeof(key));
    hex_decode(iv_hex, iv, sizeof(iv));
    pt_len = hex_decode(pt_hex, pt, sizeof(pt));
    aad_len = hex_decode(aad_hex, aad, sizeof(aad));
    nist_ct_len = hex_decode(ct_hex, nist_ct, sizeof(nist_ct));
    hex_decode(tag_hex, nist_tag, sizeof(nist_tag));
    TEST_ASSERT_EQUAL_UINT_MESSAGE(pt_len, nist_ct_len, label);

    rc = qc_aead_encrypt(key, sizeof(key), iv, sizeof(iv),
                         aad_len ? aad : NULL, aad_len,
                         pt_len ? pt : NULL, pt_len, ct, tag);
    TEST_ASSERT_EQUAL_INT_MESSAGE(QC_AEAD_OK, rc, label);
    expect_hex_n(label, ct, pt_len, ct_hex);
    expect_hex_n(label, tag, sizeof(tag), tag_hex);

    rc = qc_aead_decrypt(key, sizeof(key), iv, sizeof(iv),
                         aad_len ? aad : NULL, aad_len,
                         pt_len ? nist_ct : NULL, nist_ct_len,
                         nist_tag, back);
    TEST_ASSERT_EQUAL_INT_MESSAGE(QC_AEAD_OK, rc, label);
    if (pt_len > 0) {
        TEST_ASSERT_EQUAL_UINT8_ARRAY_MESSAGE(pt, back, pt_len, label);
    }

    /* Flip one AAD bit: must fail auth, and must not release plaintext. */
    if (aad_len > 0) {
        uint8_t bad_aad[32];
        memcpy(bad_aad, aad, aad_len);
        bad_aad[0] ^= 0x01;
        memset(back, 0x5A, sizeof(back));
        rc = qc_aead_decrypt(key, sizeof(key), iv, sizeof(iv),
                             bad_aad, aad_len, ct, pt_len, tag, back);
        TEST_ASSERT_EQUAL_INT_MESSAGE(QC_AEAD_AUTH_FAIL, rc, label);
        for (size_t i = 0; i < pt_len; i++) {
            TEST_ASSERT_EQUAL_UINT8_MESSAGE(0, back[i], label);
        }
    }
}

/* CAVP gcmEncryptExtIV256, {256, 96, 0, 0, 128}: empty PT, empty AAD. */
static void test_cavp_empty(void) {
    run_cavp("cavp empty pt/aad",
             "b52c505a37d78eda5dd34f20c22540ea1b58963cf8e5bf8ffa85f9f2492505b4",
             "516c33929df5a3284ff463d7", "", "", "",
             "bdc1ac884d332457a1d2664f168c76f0");
    run_cavp("cavp empty pt/aad #1",
             "5fe0861cdc2690ce69b3658c7f26f8458eec1c9243c5ba0845305d897e96ca0f",
             "770ac1a5a3d476d5d96944a1", "", "", "",
             "196d691e1047093ca4b3d2ef4baba216");
}

/* CAVP gcmEncryptExtIV256, {256, 96, 0, 128, 128}: empty PT, 128-bit AAD. */
static void test_cavp_aad_only(void) {
    run_cavp("cavp aad only",
             "78dc4e0aaf52d935c3c01eea57428f00ca1fd475f5da86a49c8dd73d68c8e223",
             "d79cf22d504cc793c3fb6c8a", "",
             "b96baa8c1c75a671bfb2d08d06be5f36", "",
             "3e5d486aa2e30b22e040b85723a06e76");
    run_cavp("cavp aad only #1",
             "4457ff33683cca6ca493878bdc00373893a9763412eef8cddb54f91318e0da88",
             "699d1f29d7b8c55300bb1fd2", "",
             "6749daeea367d0e9809e2dc2f309e6e3", "",
             "d60c74d2517fde4a74e0cd4709ed43a9");
}

/* CAVP gcmEncryptExtIV256, {256, 96, 128, 0, 128}: 128-bit PT, empty AAD. */
static void test_cavp_pt128(void) {
    run_cavp("cavp pt128",
             "31bdadd96698c204aa9ce1448ea94ae1fb4a9a0b3c9d773b51bb1822666b8f22",
             "0d18e06c7c725ac9e362e1ce",
             "2db5168e932556f8089a0622981d017d", "",
             "fa4362189661d163fcd6a56d8bf0405a",
             "d636ac1bbedd5cc3ee727dc2ab4a9489");
    run_cavp("cavp pt128 #1",
             "460fc864972261c2560e1eb88761ff1c992b982497bd2ac36c04071cbb8e5d99",
             "8a4a16b9e210eb68bcb6f58d",
             "99e4e926ffe927f691893fb79a96b067", "",
             "133fc15751621b5f325c7ff71ce08324",
             "ec4e87e0cf74a13618d0b68636ba9fa7");
}

/* CAVP gcmEncryptExtIV256, {256, 96, 408, 160, 128}: 51-byte PT, 20-byte
 * AAD. Multi-block with a partial final block on both inputs. */
static void test_cavp_multiblock(void) {
    run_cavp("cavp multiblock",
             "24501ad384e473963d476edcfe08205237acfd49b5b8f33857f8114e863fec7f",
             "9ff18563b978ec281b3f2794",
             "27f348f9cdc0c5bd5e66b1ccb63ad920ff2219d14e8d631b3872265cf117ee8"
             "6757accb158bd9abb3868fdc0d0b074b5f01b2c",
             "adb5ec720ccf9898500028bf34afccbcaca126ef",
             "eb7cb754c824e8d96f7c6d9b76c7d26fb874ffbf1d65c6f64a698d839b0b06"
             "145dae82057ad55994cf59ad7f67c0fa5e85fab8",
             "bc95c532fecc594c36d1550286a7a3f0");
}

/* CAVP gcmEncryptExtIV256, {256, 96, 104, 0, 128}: 13-byte PT (partial
 * final block), empty AAD. */
static void test_cavp_partial_block(void) {
    run_cavp("cavp partial block",
             "82c4f12eeec3b2d3d157b0f992d292b237478d2cecc1d5f161389b97f999057a",
             "7b40b20f5f397177990ef2d1",
             "982a296ee1cd7086afad976945", "",
             "ec8e05a0471d6b43a59ca5335f",
             "113ddeafc62373cac2f5951bb9165249");
    run_cavp("cavp partial block #1",
             "db4340af2f835a6c6d7ea0ca9d83ca81ba02c29b7410f221cb6071114e39324"
             "0",
             "40e438357dd80a85cac3349e",
             "8ddb3397bd42853193cb0f80c9", "",
             "b694118c85c41abf69e229cb0f",
             "c07f1b8aafbd152f697eb67f2a85fe45");
}

static void test_vector_empty(void) {
    uint8_t key[32], nonce[12], ct[1], tag[16], pt[1];
    int rc;

    fill_key_nonce(key, nonce);
    rc = qc_aead_encrypt(key, 32, nonce, 12, NULL, 0, NULL, 0, ct, tag);
    TEST_ASSERT_EQUAL_INT_MESSAGE(QC_AEAD_OK, rc, "enc rc");
    expect_hex_n("empty tag", tag, 16,
                 "5c699625af4b93a0f8220a2a6119c5d0");
    rc = qc_aead_decrypt(key, 32, nonce, 12, NULL, 0, NULL, 0, tag, pt);
    TEST_ASSERT_EQUAL_INT_MESSAGE(QC_AEAD_OK, rc, "dec rc");
}

static void test_vector_msg16(void) {
    uint8_t key[32], nonce[12], pt[16], ct[16], tag[16], back[16];
    static const char *aad = "header-data";
    int rc;

    fill_key_nonce(key, nonce);
    for (int i = 0; i < 16; i++) {
        pt[i] = (uint8_t)i;
    }
    rc = qc_aead_encrypt(key, 32, nonce, 12, (const uint8_t *)aad, 11,
                         pt, sizeof(pt), ct, tag);
    TEST_ASSERT_EQUAL_INT_MESSAGE(QC_AEAD_OK, rc, "enc rc");
    expect_hex_n("msg16 ct", ct, 16, "e6197e2e41ce04b86a6c8dd80b77ced1");
    expect_hex_n("msg16 tag", tag, 16, "16a76f62bad871863594584211677607");
    rc = qc_aead_decrypt(key, 32, nonce, 12, (const uint8_t *)aad, 11,
                         ct, sizeof(ct), tag, back);
    TEST_ASSERT_EQUAL_INT_MESSAGE(QC_AEAD_OK, rc, "dec rc");
    TEST_ASSERT_EQUAL_UINT8_ARRAY_MESSAGE(pt, back, 16, "roundtrip");
}

static void test_vector_msg64(void) {
    uint8_t key[32], nonce[12], pt[64], ct[64], tag[16], back[64];
    int rc;

    fill_key_nonce(key, nonce);
    for (int i = 0; i < 64; i++) {
        pt[i] = (uint8_t)i;
    }
    rc = qc_aead_encrypt(key, 32, nonce, 12, NULL, 0, pt, sizeof(pt),
                         ct, tag);
    TEST_ASSERT_EQUAL_INT_MESSAGE(QC_AEAD_OK, rc, "enc rc");
    expect_hex_n("msg64 ct", ct, 64,
                 "e6197e2e41ce04b86a6c8dd80b77ced160bd4b0386a2547b84173c9d63b66b1ef"
                 "25765dc8b07751a77b52ee32557add6772a747b56e52c4979673165984dbb8f");
    expect_hex_n("msg64 tag", tag, 16, "4be5bfb71996c6878070dad5bf997021");
    rc = qc_aead_decrypt(key, 32, nonce, 12, NULL, 0, ct, sizeof(ct),
                         tag, back);
    TEST_ASSERT_EQUAL_INT_MESSAGE(QC_AEAD_OK, rc, "dec rc");
    TEST_ASSERT_EQUAL_UINT8_ARRAY_MESSAGE(pt, back, 64, "roundtrip");
}

/* Every input-validation branch in qc_aead.c gets at least one test.
 * check_common: NULL key, NULL nonce, short key, short nonce — on both
 * paths. Per-call guards: NULL pt/ct/tag/aad with nonzero length —
 * on both paths. */
static void test_null_guards_encrypt(void) {
    uint8_t key[32], nonce[12], pt[16], ct[16], tag[16];
    int rc;

    fill_key_nonce(key, nonce);
    memset(pt, 0x33, sizeof(pt));
    rc = qc_aead_encrypt(key, 32, nonce, 12, NULL, 0, pt, sizeof(pt),
                         ct, tag);
    TEST_ASSERT_EQUAL_INT(QC_AEAD_OK, rc);

    TEST_ASSERT_EQUAL_INT(QC_AEAD_BAD_KEY,
                          qc_aead_encrypt(NULL, 32, nonce, 12, NULL, 0,
                                          pt, sizeof(pt), ct, tag));
    TEST_ASSERT_EQUAL_INT(QC_AEAD_BAD_LENGTH,
                          qc_aead_encrypt(key, 32, NULL, 12, NULL, 0,
                                          pt, sizeof(pt), ct, tag));
    TEST_ASSERT_EQUAL_INT(QC_AEAD_BAD_KEY,
                          qc_aead_encrypt(key, 16, nonce, 12, NULL, 0,
                                          pt, sizeof(pt), ct, tag));
    TEST_ASSERT_EQUAL_INT(QC_AEAD_BAD_LENGTH,
                          qc_aead_encrypt(key, 32, nonce, 11, NULL, 0,
                                          pt, sizeof(pt), ct, tag));
    TEST_ASSERT_EQUAL_INT(QC_AEAD_BAD_LENGTH,
                          qc_aead_encrypt(key, 32, nonce, 12, NULL, 0,
                                          NULL, sizeof(pt), ct, tag));
    TEST_ASSERT_EQUAL_INT(QC_AEAD_BAD_LENGTH,
                          qc_aead_encrypt(key, 32, nonce, 12, NULL, 0,
                                          pt, sizeof(pt), NULL, tag));
    TEST_ASSERT_EQUAL_INT(QC_AEAD_BAD_LENGTH,
                          qc_aead_encrypt(key, 32, nonce, 12, NULL, 0,
                                          pt, sizeof(pt), ct, NULL));
    TEST_ASSERT_EQUAL_INT(QC_AEAD_BAD_LENGTH,
                          qc_aead_encrypt(key, 32, nonce, 12, NULL, 1,
                                          pt, sizeof(pt), ct, tag));
}

static void test_null_guards_decrypt(void) {
    uint8_t key[32], nonce[12], pt[16], ct[16], tag[16], back[16];
    int rc;

    fill_key_nonce(key, nonce);
    memset(pt, 0x33, sizeof(pt));
    memset(back, 0, sizeof(back));
    rc = qc_aead_encrypt(key, 32, nonce, 12, NULL, 0, pt, sizeof(pt),
                         ct, tag);
    TEST_ASSERT_EQUAL_INT(QC_AEAD_OK, rc);

    TEST_ASSERT_EQUAL_INT(QC_AEAD_BAD_KEY,
                          qc_aead_decrypt(NULL, 32, nonce, 12, NULL, 0,
                                          ct, sizeof(ct), tag, back));
    TEST_ASSERT_EQUAL_INT(QC_AEAD_BAD_LENGTH,
                          qc_aead_decrypt(key, 32, NULL, 12, NULL, 0,
                                          ct, sizeof(ct), tag, back));
    TEST_ASSERT_EQUAL_INT(QC_AEAD_BAD_KEY,
                          qc_aead_decrypt(key, 24, nonce, 12, NULL, 0,
                                          ct, sizeof(ct), tag, back));
    TEST_ASSERT_EQUAL_INT(QC_AEAD_BAD_LENGTH,
                          qc_aead_decrypt(key, 32, nonce, 11, NULL, 0,
                                          ct, sizeof(ct), tag, back));
    TEST_ASSERT_EQUAL_INT(QC_AEAD_BAD_LENGTH,
                          qc_aead_decrypt(key, 32, nonce, 12, NULL, 0,
                                          NULL, sizeof(ct), tag, back));
    TEST_ASSERT_EQUAL_INT(QC_AEAD_BAD_LENGTH,
                          qc_aead_decrypt(key, 32, nonce, 12, NULL, 0,
                                          ct, sizeof(ct), tag, NULL));
    TEST_ASSERT_EQUAL_INT(QC_AEAD_BAD_LENGTH,
                          qc_aead_decrypt(key, 32, nonce, 12, NULL, 0,
                                          ct, sizeof(ct), NULL, back));
    TEST_ASSERT_EQUAL_INT(QC_AEAD_BAD_LENGTH,
                          qc_aead_decrypt(key, 32, nonce, 12, NULL, 1,
                                          ct, sizeof(ct), tag, back));
    /* Empty input with NULL buffers is legal (length 0 touches nothing).
     * Needs the tag for the empty message, not the tag from above. */
    {
        uint8_t empty_tag[16];
        TEST_ASSERT_EQUAL_INT(QC_AEAD_OK,
                              qc_aead_encrypt(key, 32, nonce, 12, NULL, 0,
                                              NULL, 0, NULL, empty_tag));
        TEST_ASSERT_EQUAL_INT(QC_AEAD_OK,
                              qc_aead_decrypt(key, 32, nonce, 12, NULL, 0,
                                              NULL, 0, empty_tag, back));
    }
}

/* Tamper events -> AUTH_FAIL with output wiped; overlap -> BAD_LENGTH
 * (caller bug, never a tamper event); in-place (pt == ct) is legal. */
static void test_misuse_taxonomy(void) {
    uint8_t key[32], nonce[12], pt[16], ct[16], tag[16], back[16];
    uint8_t badtag[16], buf[17];
    int rc;

    fill_key_nonce(key, nonce);
    for (int i = 0; i < 16; i++) {
        pt[i] = (uint8_t)(0x30 + i);
    }
    rc = qc_aead_encrypt(key, 32, nonce, 12, NULL, 0, pt, sizeof(pt),
                         ct, tag);
    TEST_ASSERT_EQUAL_INT(QC_AEAD_OK, rc);

    /* Tampered tag -> AUTH_FAIL, output wiped. */
    memcpy(badtag, tag, 16);
    badtag[0] ^= 0x01;
    memset(back, 0x5A, sizeof(back));
    rc = qc_aead_decrypt(key, 32, nonce, 12, NULL, 0, ct, sizeof(ct),
                         badtag, back);
    TEST_ASSERT_EQUAL_INT_MESSAGE(QC_AEAD_AUTH_FAIL, rc, "tamper");
    for (size_t i = 0; i < sizeof(back); i++) {
        TEST_ASSERT_EQUAL_UINT8_MESSAGE(0, back[i], "wiped on fail");
    }
    /* Tampered ciphertext -> AUTH_FAIL. */
    ct[0] ^= 0x01;
    TEST_ASSERT_EQUAL_INT(QC_AEAD_AUTH_FAIL,
                          qc_aead_decrypt(key, 32, nonce, 12, NULL, 0,
                                          ct, sizeof(ct), tag, back));
    ct[0] ^= 0x01; /* restore */

    /* In-place encrypt and decrypt (pt == ct) are supported. */
    memcpy(back, pt, sizeof(pt));
    rc = qc_aead_encrypt(key, 32, nonce, 12, NULL, 0,
                         back, sizeof(back), back, tag);
    TEST_ASSERT_EQUAL_INT_MESSAGE(QC_AEAD_OK, rc, "in-place enc");
    TEST_ASSERT_EQUAL_UINT8_ARRAY_MESSAGE(ct, back, 16, "in-place ct");
    memcpy(back, ct, sizeof(ct));
    rc = qc_aead_decrypt(key, 32, nonce, 12, NULL, 0,
                         back, sizeof(back), tag, back);
    TEST_ASSERT_EQUAL_INT_MESSAGE(QC_AEAD_OK, rc, "in-place");
    TEST_ASSERT_EQUAL_UINT8_ARRAY_MESSAGE(pt, back, 16, "in-place pt");

    /* Forward overlap (output starts inside the input region) is a
     * caller bug: BAD_LENGTH, never AUTH_FAIL. Only this direction is
     * rejected by the backend; backward overlap is not contracted, so
     * the test pins only the rejected direction. */
    memcpy(buf, pt, 16);
    rc = qc_aead_encrypt(key, 32, nonce, 12, NULL, 0,
                         buf, 16, buf + 1, tag);
    TEST_ASSERT_EQUAL_INT_MESSAGE(QC_AEAD_BAD_LENGTH, rc, "overlap enc");
    memcpy(buf, ct, 16);
    rc = qc_aead_decrypt(key, 32, nonce, 12, NULL, 0,
                         buf, 16, tag, buf + 1);
    TEST_ASSERT_EQUAL_INT_MESSAGE(QC_AEAD_BAD_LENGTH, rc, "overlap dec");
}

void setUp(void) {}
void tearDown(void) {}

int main(void) {
    UNITY_BEGIN();
    /* Official NIST CAVP vectors (primary correctness evidence). */
    RUN_TEST(test_cavp_empty);
    RUN_TEST(test_cavp_aad_only);
    RUN_TEST(test_cavp_pt128);
    RUN_TEST(test_cavp_multiblock);
    RUN_TEST(test_cavp_partial_block);
    /* Cross-implementation agreement (regression guard). */
    RUN_TEST(test_vector_empty);
    RUN_TEST(test_vector_msg16);
    RUN_TEST(test_vector_msg64);
    /* Misuse taxonomy. */
    RUN_TEST(test_null_guards_encrypt);
    RUN_TEST(test_null_guards_decrypt);
    RUN_TEST(test_misuse_taxonomy);
    return UNITY_END();
}
