/* test_kem.c — L0/L1 for the ML-KEM adapter (B-10).
 *
 * KAT source: tests/c/mlkem_vectors.h, copied verbatim from
 * mlkem-native v2.0.0 examples/multilevel_build/
 * expected_test_vectors_multilevel.h (auto-generated by upstream from
 * notrandombytes streams; same coins drive our derandomized APIs).
 * Coins: keygen d||z (64 B), encaps m (32 B) — shared across levels.
 * Independently cross-checked with Python (FIPS 203 reference arithmetic
 * is out of scope for the oracle; agreement here is backend-vs-vectors,
 * and the vectors are additionally ACVP/Wycheproof-covered upstream).
 */
#include "unity.h"

#include <string.h>

#include "qc_kem.h"
#include "mlkem_vectors.h"

static void fill_coins(uint8_t keygen64[64], uint8_t encaps32[32]) {
    memcpy(keygen64, test_vector_d, 32);
    memcpy(keygen64 + 32, test_vector_z, 32);
    memcpy(encaps32, test_vector_m, 32);
}

/* One level: KAT keygen -> KAT encaps -> decaps roundtrip, all against
 * published vectors. */
static void run_kat(qc_kem_level level,
                    const uint8_t *want_pk, const uint8_t *want_sk,
                    const uint8_t *want_ct, const uint8_t *want_ss,
                    const char *label) {
    /* Max sizes cover 1024; per-level asserts below use real lengths. */
    static uint8_t pk[1568], sk[3168], ct[1568], ss[32], back[32];
    uint8_t keygen_coins[64], encaps_coins[32];
    size_t pk_len = qc_kem_pk_bytes(level);
    size_t sk_len = qc_kem_sk_bytes(level);
    size_t ct_len = qc_kem_ct_bytes(level);
    int rc;

    TEST_ASSERT_TRUE_MESSAGE(pk_len > 0, label);
    fill_coins(keygen_coins, encaps_coins);

    rc = qc_kem_keypair(level, pk, sk, keygen_coins);
    TEST_ASSERT_EQUAL_INT_MESSAGE(QC_KEM_OK, rc, label);
    TEST_ASSERT_EQUAL_UINT8_ARRAY_MESSAGE(want_pk, pk, pk_len, label);
    TEST_ASSERT_EQUAL_UINT8_ARRAY_MESSAGE(want_sk, sk, sk_len, label);

    rc = qc_kem_encaps(level, ct, ss, pk, encaps_coins);
    TEST_ASSERT_EQUAL_INT_MESSAGE(QC_KEM_OK, rc, label);
    TEST_ASSERT_EQUAL_UINT8_ARRAY_MESSAGE(want_ct, ct, ct_len, label);
    TEST_ASSERT_EQUAL_UINT8_ARRAY_MESSAGE(want_ss, ss, 32, label);

    rc = qc_kem_decaps(level, back, ct, sk);
    TEST_ASSERT_EQUAL_INT_MESSAGE(QC_KEM_OK, rc, label);
    TEST_ASSERT_EQUAL_UINT8_ARRAY_MESSAGE(ss, back, 32, label);
}

static void test_kat_512(void) {
    run_kat(QC_KEM_512, test_vector_pk_512, test_vector_sk_512,
            test_vector_ct_512, test_vector_ss_512, "kat512");
}

static void test_kat_768(void) {
    run_kat(QC_KEM_768, test_vector_pk_768, test_vector_sk_768,
            test_vector_ct_768, test_vector_ss_768, "kat768");
}

static void test_kat_1024(void) {
    run_kat(QC_KEM_1024, test_vector_pk_1024, test_vector_sk_1024,
            test_vector_ct_1024, test_vector_ss_1024, "kat1024");
}

/* Implicit rejection on every level: tampered ct decapsulates OK but to
 * an unrelated ss. Authenticity must come from the transcript MAC, never
 * from decaps. Buffers sized for 1024; per-level lengths asserted. */
static void run_rejection(qc_kem_level level, const char *label) {
    static uint8_t pk[1568], sk[3168], ct[1568], ss[32], back[32];
    uint8_t keygen_coins[64], encaps_coins[32];
    size_t pk_len = qc_kem_pk_bytes(level);
    size_t ct_len = qc_kem_ct_bytes(level);
    int rc;

    TEST_ASSERT_TRUE_MESSAGE(pk_len > 0 && ct_len > 0, label);
    fill_coins(keygen_coins, encaps_coins);
    TEST_ASSERT_EQUAL_INT_MESSAGE(QC_KEM_OK,
                                  qc_kem_keypair(level, pk, sk, keygen_coins),
                                  label);
    TEST_ASSERT_EQUAL_INT_MESSAGE(QC_KEM_OK,
                                  qc_kem_encaps(level, ct, ss, pk, encaps_coins),
                                  label);
    ct[0] ^= 0x01;
    ct[ct_len - 1] ^= 0x80;
    rc = qc_kem_decaps(level, back, ct, sk);
    TEST_ASSERT_EQUAL_INT_MESSAGE(QC_KEM_OK, rc, label);
    TEST_ASSERT_TRUE_MESSAGE(memcmp(ss, back, 32) != 0, label);
}

static void test_implicit_rejection(void) {
    run_rejection(QC_KEM_512, "rej512");
    run_rejection(QC_KEM_768, "rej768");
    run_rejection(QC_KEM_1024, "rej1024");
}

/* Malformed pk: first coefficient forced to 0xFFF (>= q=3329), so the
 * FIPS 203 modulus check must fail -> BAD_KEY, never OK. */
static void test_bad_pk(void) {
    static uint8_t pk[1184], ct[1088], ss[32];
    uint8_t keygen_coins[64], encaps_coins[32];

    fill_coins(keygen_coins, encaps_coins);
    memcpy(pk, test_vector_pk_768, sizeof(pk));
    pk[0] = 0xFF;
    pk[1] |= 0x0F;
    TEST_ASSERT_EQUAL_INT(QC_KEM_BAD_KEY,
                          qc_kem_encaps(QC_KEM_768, ct, ss, pk, encaps_coins));
}

/* Corrupt sk: flip a byte in the embedded H(pk) region (last 64 bytes
 * are H||z, so sk_len-64 is inside H) -> hash check fails -> BAD_KEY. */
static void test_bad_sk(void) {
    static uint8_t back[32];
    static uint8_t sk[2400];
    int rc;

    memcpy(sk, test_vector_sk_768, sizeof(sk));
    sk[sizeof(sk) - 64] ^= 0x01;
    rc = qc_kem_decaps(QC_KEM_768, back, test_vector_ct_768, sk);
    TEST_ASSERT_EQUAL_INT_MESSAGE(QC_KEM_BAD_KEY, rc, "bad sk");
}

/* Misuse taxonomy: bad level + NULL buffers on every API. */
static void test_misuse(void) {
    static uint8_t pk[1184], sk[2400], ct[1088], ss[32];
    uint8_t keygen_coins[64], encaps_coins[32];

    fill_coins(keygen_coins, encaps_coins);

    TEST_ASSERT_EQUAL_INT(QC_KEM_BAD_LEVEL,
                          qc_kem_keypair(0, pk, sk, keygen_coins));
    TEST_ASSERT_EQUAL_INT(QC_KEM_BAD_LEVEL,
                          qc_kem_encaps(256, ct, ss, pk, encaps_coins));
    TEST_ASSERT_EQUAL_INT(QC_KEM_BAD_LEVEL,
                          qc_kem_decaps(999, ss, ct, sk));
    TEST_ASSERT_EQUAL_INT(QC_KEM_BAD_LENGTH,
                          qc_kem_keypair(QC_KEM_768, NULL, sk, keygen_coins));
    TEST_ASSERT_EQUAL_INT(QC_KEM_BAD_LENGTH,
                          qc_kem_keypair(QC_KEM_768, pk, NULL, keygen_coins));
    TEST_ASSERT_EQUAL_INT(QC_KEM_BAD_LENGTH,
                          qc_kem_keypair(QC_KEM_768, pk, sk, NULL));
    TEST_ASSERT_EQUAL_INT(QC_KEM_BAD_LENGTH,
                          qc_kem_encaps(QC_KEM_768, NULL, ss, pk, encaps_coins));
    TEST_ASSERT_EQUAL_INT(QC_KEM_BAD_LENGTH,
                          qc_kem_encaps(QC_KEM_768, ct, NULL, pk, encaps_coins));
    TEST_ASSERT_EQUAL_INT(QC_KEM_BAD_LENGTH,
                          qc_kem_encaps(QC_KEM_768, ct, ss, NULL, encaps_coins));
    TEST_ASSERT_EQUAL_INT(QC_KEM_BAD_LENGTH,
                          qc_kem_encaps(QC_KEM_768, ct, ss, pk, NULL));
    TEST_ASSERT_EQUAL_INT(QC_KEM_BAD_LENGTH,
                          qc_kem_decaps(QC_KEM_768, NULL, ct, sk));
    TEST_ASSERT_EQUAL_INT(QC_KEM_BAD_LENGTH,
                          qc_kem_decaps(QC_KEM_768, ss, NULL, sk));
    TEST_ASSERT_EQUAL_INT(QC_KEM_BAD_LENGTH,
                          qc_kem_decaps(QC_KEM_768, ss, ct, NULL));

    TEST_ASSERT_EQUAL_UINT(QC_KEM512_PK_BYTES, qc_kem_pk_bytes(QC_KEM_512));
    TEST_ASSERT_EQUAL_UINT(QC_KEM768_PK_BYTES, qc_kem_pk_bytes(QC_KEM_768));
    TEST_ASSERT_EQUAL_UINT(QC_KEM1024_PK_BYTES, qc_kem_pk_bytes(QC_KEM_1024));
    TEST_ASSERT_EQUAL_UINT(QC_KEM512_SK_BYTES, qc_kem_sk_bytes(QC_KEM_512));
    TEST_ASSERT_EQUAL_UINT(QC_KEM768_SK_BYTES, qc_kem_sk_bytes(QC_KEM_768));
    TEST_ASSERT_EQUAL_UINT(QC_KEM1024_SK_BYTES, qc_kem_sk_bytes(QC_KEM_1024));
    TEST_ASSERT_EQUAL_UINT(QC_KEM512_CT_BYTES, qc_kem_ct_bytes(QC_KEM_512));
    TEST_ASSERT_EQUAL_UINT(QC_KEM768_CT_BYTES, qc_kem_ct_bytes(QC_KEM_768));
    TEST_ASSERT_EQUAL_UINT(QC_KEM1024_CT_BYTES, qc_kem_ct_bytes(QC_KEM_1024));
    TEST_ASSERT_EQUAL_UINT(0, qc_kem_pk_bytes(0));
    TEST_ASSERT_EQUAL_UINT(0, qc_kem_sk_bytes(256));
    TEST_ASSERT_EQUAL_UINT(0, qc_kem_ct_bytes(999));
}

/* Release wrappers (B-10.4): exact extents wiped on every level, tail
 * past the extent untouched (proves no over-wipe, not just no
 * under-wipe), return codes honest, bad level wipes nothing. */
static void test_free_wrappers(void) {
    static const qc_kem_level levels[3] = {
        QC_KEM_512, QC_KEM_768, QC_KEM_1024
    };
    static uint8_t sk[3168], ss[32];

    for (int l = 0; l < 3; l++) {
        size_t n = qc_kem_sk_bytes(levels[l]);
        TEST_ASSERT_TRUE_MESSAGE(n > 0 && n <= sizeof(sk), "extent");
        memset(sk, 0xA5, sizeof(sk));
        TEST_ASSERT_EQUAL_INT_MESSAGE(QC_KEM_OK,
                                      qc_kem_free_sk(levels[l], sk), "rc");
        for (size_t i = 0; i < n; i++) {
            TEST_ASSERT_EQUAL_UINT8_MESSAGE(0, sk[i], "wiped");
        }
        for (size_t i = n; i < sizeof(sk); i++) {
            TEST_ASSERT_EQUAL_UINT8_MESSAGE(0xA5, sk[i], "tail intact");
        }
    }
    memset(ss, 0xA5, sizeof(ss));
    qc_kem_free_ss(ss);
    for (size_t i = 0; i < sizeof(ss); i++) {
        TEST_ASSERT_EQUAL_UINT8_MESSAGE(0, ss[i], "ss wiped");
    }
    /* NULL-safe. */
    TEST_ASSERT_EQUAL_INT(QC_KEM_OK, qc_kem_free_sk(QC_KEM_768, NULL));
    qc_kem_free_ss(NULL);
    /* Bad level: return signals failure AND nothing is wiped. */
    memset(sk, 0xA5, sizeof(sk));
    TEST_ASSERT_EQUAL_INT(QC_KEM_BAD_LEVEL, qc_kem_free_sk(0, sk));
    for (size_t i = 0; i < sizeof(sk); i++) {
        TEST_ASSERT_EQUAL_UINT8_MESSAGE(0xA5, sk[i], "untouched");
    }
}

void setUp(void) {}
void tearDown(void) {}

int main(void) {
    UNITY_BEGIN();
    RUN_TEST(test_kat_512);
    RUN_TEST(test_kat_768);
    RUN_TEST(test_kat_1024);
    RUN_TEST(test_implicit_rejection);
    RUN_TEST(test_bad_pk);
    RUN_TEST(test_bad_sk);
    RUN_TEST(test_misuse);
    RUN_TEST(test_free_wrappers);
    return UNITY_END();
}