#!/usr/bin/env python3
"""drbg_to_c.py — convert NIST CAVS HMAC_DRBG vectors to a C header.

Source: mbedTLS test_suite_hmac_drbg.nopr.data (NIST CAVS 14.3 vectors,
SHA-256, no prediction resistance), fetched Oct 2026 — see
tools/fetch_drbg.py (dev helper, uncommitted scratch).
Vector form per case mirrors the mbedTLS hmac_drbg_nopr driver sequence
exactly (verified against test_suite_hmac_drbg.function AND
mbedtls_hmac_drbg.c reseed_core): seed draws 48 B from the entropy
stream (entropy_len 32 + 16 B nonce) and Updates seed=ent[:48]+custom;
reseed(add1) draws the NEXT 32 B from the stream and Updates
r1=ent[48:80]+add1; then generate(add2) [discarded output],
generate(add3) -> returned bits compared. Update() is NOT concatenable,
so the 48/32 entropy split must be preserved here — seed=ent+custom as a
single reseed FAILS KAT (found 2026-10-10: first byte 0x73 vs 0x76).

SELECTION: 4 vectors from each of the 4 shape classes
(ent-only; ent+pers+adds; ent+nonce; all fields) = 16 KATs. Deterministic
subset; the full 60-vector file is the nightly option (edit STRIDE).
Output: tests/c/drbg_vectors.h with hex tables (chunked literals).
"""
import json
import sys

STRIDE = 4


def hx(s):
    assert all(c in "0123456789abcdefABCDEF" for c in s), "non-hex"
    assert len(s) % 2 == 0, "odd hex"
    return s.lower()


def cstr(s, width=2000):
    s = hx(s)
    parts = [s[i:i + width] for i in range(0, len(s), width)] or [""]
    return " ".join(f'"{p}"' for p in parts)


def load(path):
    with open(path, encoding="utf-8") as f:
        return f.read().splitlines()


# mbedTLS driver sequence (test_suite_hmac_drbg.function, hmac_drbg_nopr):
#   seed(entropy, custom) -> reseed(add1) -> gen(add2) [discard] ->
#   gen(add3) [compare]. The .data columns are
#   (entropy, custom, add1, add2, add3, output) — NOT (nonce/pers/adds).


def main():
    src, outpath = sys.argv[1], sys.argv[2]
    lines = load(src)
    # group data lines by preceding header comment class
    classes = {}
    cur = None
    for i, l in enumerate(lines):
        if l.startswith("HMAC_DRBG NIST CAVS") and "SHA-256" in l:
            cur = l
        elif l.startswith("hmac_drbg_nopr:MBEDTLS_MD_SHA256:") and cur:
            classes.setdefault(cur, []).append(l)
    L = []
    A = L.append
    A("/* drbg_vectors.h -- AUTO-GENERATED by tools/drbg_to_c.py.")
    A(" * NIST CAVS 14.3 HMAC_DRBG SHA-256 no-PR vectors via mbedTLS test")
    A(" * data. DO NOT EDIT. See the SELECTION RULE in the script. */")
    A("#ifndef DRBG_VECTORS_H")
    A("#define DRBG_VECTORS_H")
    A("")
    A("#include <stddef.h>")
    A("#include <stdint.h>")
    A("")
    A("typedef struct { const char *seed, *r1, *g1, *g2, *out; } wy_drbg_t;")
    A("")
    # Regroup the 60 per-case headers into the 4 shape classes by
    # (nonce_len, pers_len); stride within each class.
    by_shape = {}
    for hdr, vecs in classes.items():
        for v in vecs:
            f = [x.strip('"') for x in v.split(":")[2:]]
            key = (len(f[1]), len(f[3]))
            by_shape.setdefault(key, []).append((hdr, v))
    total = 0
    for ci, (shape, items) in enumerate(sorted(by_shape.items())):
        hdr0 = items[0][0]
        vecs = [v for _, v in items]
        sel = vecs[::STRIDE]
        A(f"/* shape (custom,add2) hexlens {shape} e.g. {hdr0[:70]} "
          f"(showing {len(sel)}/{len(vecs)}) */")
        A(f"static const wy_drbg_t wy_drbg_{ci}[] = {{")
        for v in sel:
            f = [x.strip('"') for x in v.split(":")[2:]]
            ent, custom, r1, g1, g2, ret = f[0], f[1], f[2], f[3], f[4], f[5]
            # SHA-256 entropy_len=32: seed consumes 48 B (32+16 nonce),
            # reseed consumes the next 32 B. ent is 80 B (160 hex) here.
            assert len(ent) == 160, f"unexpected ent hexlen {len(ent)}"
            seed = ent[:96] + custom
            r1 = ent[96:] + r1
            assert ret, "empty output"
            A(f"    {{ {cstr(seed)}, {cstr(r1)}, {cstr(g1)}, {cstr(g2)}, {cstr(ret)} }},")
            total += 1
        A("};")
        A(f"static const size_t wy_drbg_{ci}_n = {len(sel)};")
        A("")
    A("#endif")
    open(outpath, "w", encoding="utf-8").write("\n".join(L))
    print("wrote", outpath, total, "vectors")


if __name__ == "__main__":
    main()
