#!/usr/bin/env python3
"""wycheproof_to_c.py — convert Wycheproof JSON vectors to a C header.

Independent cross-check input (B-10.3/B-11.3): vectors generated by
implementations other than mlkem-native/mldsa-native, driven through our
adapters byte-for-byte.

Usage (run from repo root; needs the upstream JSON files):
  python tools/wycheproof_to_c.py <json-dir> tests/c/wycheproof_xcheck.h

Upstream source (pinned set, Oct 2026):
  https://raw.githubusercontent.com/C2SP/wycheproof/main/testvectors_v1/
  mlkem_{512,768,1024}_{keygen_seed,encaps}_test.json
  mldsa_{44,65,87}_{sign_seed,verify}_test.json

SELECTION RULE (deterministic; full files are the nightly option):
  The full corpus (~13 MB JSON, ~1700 tests) is too large to vendor as C.
  This script takes a fixed stride subset plus ALL same-shape negatives:
  - KEM keygen_seed (all valid): every 7th test -> {seed64, ek, dk}.
  - KEM encaps valid: every 7th -> {ek, m32, c, K}.
  - KEM encaps invalid, FULL-LENGTH ek only (ModulusOverflow): every 7th
    -> {ek} expect BAD_KEY. Wrong-length eks are inexpressible in the
    fixed-size adapter API (skipped by construction, noted here).
  - DSA keygen: ALL sign_seed groups -> {seed32, pk} (small).
  - DSA verify, same-siglen + good-pk-group only: every 7th valid, every
    3rd invalid -> {pk(group), msg, sig, expect}. Wrong-length sig/pk
    vectors are inexpressible in the fixed-size API (skipped here).
  DSA sign_seed sign-vectors are NOT converted (rnd undisclosed for the
  deterministic subset; our KATs already cover deterministic signing).

Output: a header with hex-string tables + counts + this provenance block.
Regenerate with stride 1 (edit STRIDE below) for the full nightly gate.
"""
import json
import sys

STRIDE_VALID = 7
STRIDE_INVALID = 3

KEM_LEVELS = (512, 768, 1024)
DSA_LEVELS = (44, 65, 87)
KEM_PK = {512: 800, 768: 1184, 1024: 1568}
KEM_SK = {512: 1632, 768: 2400, 1024: 3168}
KEM_CT = {512: 768, 768: 1088, 1024: 1568}
DSA_PK = {44: 1312, 65: 1952, 87: 2592}
DSA_SIG = {44: 2420, 65: 3309, 87: 4627}


def load(d, name):
    with open(f"{d}/{name}", encoding="utf-8") as f:
        return json.load(f)


def hx(s):
    assert all(c in "0123456789abcdefABCDEF" for c in s), "non-hex"
    assert len(s) % 2 == 0, "odd hex would truncate a nibble"
    return s.lower()


def cstr(s, width=2000):
    # Split long hex into adjacent literals: C99 requires only 4095
    # bytes per literal (-Werror=overlength-strings); concatenation is
    # transparent to the reader (hex_decode takes the joined string).
    s = hx(s)
    parts = [s[i:i + width] for i in range(0, len(s), width)] or [""]
    return " ".join(f'"{p}"' for p in parts)


def emit_array(out, name, rows):
    out.append(f"static const wycheproof_kem_keygen_t {name}[] = {{")
    for r in rows:
        out.append(f'    {{ "{r[0]}", "{r[1]}", "{r[2]}" }},')
    out.append("};")
    out.append(f"static const size_t {name}_n = {len(rows)};")
    out.append("")


def main():
    indir, outpath = sys.argv[1], sys.argv[2]
    n = {"kem_keygen": 0, "kem_enc": 0, "kem_bad": 0,
         "dsa_keygen": 0, "dsa_verify": 0}
    L = []
    A = L.append
    A("/* wycheproof_xcheck.h -- AUTO-GENERATED by tools/wycheproof_to_c.py.")
    A(" * DO NOT EDIT. Regenerate from the pinned upstream JSON set; see the")
    A(" * SELECTION RULE in the script for the subsample policy.")
    A(" * Upstream: https://github.com/C2SP/wycheproof testvectors_v1,")
    A(" * mlkem_{512,768,1024}_{keygen_seed,encaps}_test.json,")
    A(" * mldsa_{44,65,87}_{sign_seed,verify}_test.json (fetched Oct 2026).")
    A(" */")
    A("#ifndef WYCHEPROOF_XCHECK_H")
    A("#define WYCHEPROOF_XCHECK_H")
    A("")
    A('#include <stddef.h>')
    A("#include <stdint.h>")
    A("")
    A("typedef struct { const char *seed, *ek, *dk; } wy_kem_keygen_t;")
    A("typedef struct { const char *ek, *m, *c, *k; } wy_kem_enc_t;")
    A("typedef struct { const char *ek; } wy_kem_bad_t;")
    A("typedef struct { const char *seed, *pk; } wy_dsa_keygen_t;")
    A("/* expect: 0 = OK, 4 = BAD_SIG, 2 = BAD_LENGTH (qc_dsa_rc values). */")
    A("typedef struct { const char *pk, *msg, *sig, *ctx; int expect; } wy_dsa_verify_t;")
    A("")

    for lvl in KEM_LEVELS:
        pk, sk, ct = KEM_PK[lvl], KEM_SK[lvl], KEM_CT[lvl]
        # keygen_seed: every 7th valid
        d = load(indir, f"mlkem_{lvl}_keygen_seed_test.json")
        tests = [t for g in d["testGroups"] for t in g["tests"]
                 if t.get("result") == "valid"]
        rows = []
        for t in tests[::STRIDE_VALID]:
            assert len(t["seed"]) // 2 == 64, t["tcId"]
            assert len(t["ek"]) // 2 == pk and len(t["dk"]) // 2 == sk, t["tcId"]
            rows.append((hx(t["seed"]), hx(t["ek"]), hx(t["dk"])))
        n["kem_keygen"] += len(rows)
        A(f"static const wy_kem_keygen_t wy_kem_keygen_{lvl}[] = {{")
        for s, e, k in rows:
            A(f'    {{ {cstr(s)},')
            A(f'      {cstr(e)},')
            A(f'      {cstr(k)} }},')
        A("};")
        A(f"static const size_t wy_kem_keygen_{lvl}_n = {len(rows)};")
        A("")
        # encaps
        d = load(indir, f"mlkem_{lvl}_encaps_test.json")
        ok_rows, bad_rows = [], []
        skipped_len = 0
        for t in [t for g in d["testGroups"] for t in g["tests"]]:
            if t.get("result") == "valid":
                ok_rows.append(t)
            elif len(t.get("ek", "")) // 2 == pk:
                # Pinned corpus: every full-length invalid here is either
                # ModulusOverflow-flagged or "Public key not reduced" —
                # both are coefficient-range violations the backend's
                # FIPS 203 modulus check rejects (BAD_KEY oracle).
                # Anything else must fail loudly, not silently join the
                # BAD_KEY bin.
                assert t.get("result") == "invalid", t.get("tcId")
                flags = t.get("flags", [])
                assert ("ModulusOverflow" in flags
                        or t.get("comment") == "Public key not reduced"), \
                    (t.get("tcId"), flags)
                bad_rows.append(t)
            else:
                skipped_len += 1
        print(f"kem{lvl} encaps wrong-length skips={skipped_len}")
        ok_sel = [t for i, t in enumerate(ok_rows) if i % STRIDE_VALID == 0]
        bad_sel = [t for i, t in enumerate(bad_rows) if i % STRIDE_INVALID == 0]
        for t in ok_sel:
            assert len(t["m"]) // 2 == 32 and len(t["ek"]) // 2 == pk, t["tcId"]
            assert len(t["c"]) // 2 == ct and len(t["K"]) // 2 == 32, t["tcId"]
        n["kem_enc"] += len(ok_sel)
        n["kem_bad"] += len(bad_sel)
        A(f"static const wy_kem_enc_t wy_kem_enc_{lvl}[] = {{")
        for t in ok_sel:
            A(f'    {{ {cstr(t["ek"])}, {cstr(t["m"])}, {cstr(t["c"])}, {cstr(t["K"])} }},')
        A("};")
        A(f"static const size_t wy_kem_enc_{lvl}_n = {len(ok_sel)};")
        A(f"static const wy_kem_bad_t wy_kem_bad_{lvl}[] = {{")
        for t in bad_sel:
            A(f'    {{ {cstr(t["ek"])} }},')
        A("};")
        A(f"static const size_t wy_kem_bad_{lvl}_n = {len(bad_sel)};")
        A("")

    for lvl in DSA_LEVELS:
        pk, sig = DSA_PK[lvl], DSA_SIG[lvl]
        # keygen: all groups with a 32B seed and full pk. The
        # IncorrectPrivateKeyLength groups (0/31/33B seeds, no pk) are
        # inexpressible in the fixed-size adapter API (seed is always
        # 32B, no length parameter exists) — skipped by construction.
        d = load(indir, f"mldsa_{lvl}_sign_seed_test.json")
        rows = []
        skipped = 0
        for g in d["testGroups"]:
            s = g.get("privateSeed") or ""
            p = g.get("publicKey") or ""
            if len(s) // 2 != 32 or len(p) // 2 != pk:
                skipped += 1
                continue
            rows.append((hx(s), hx(p)))
        print(f"dsa{ lvl} keygen groups kept={len(rows)} skipped-malformed={skipped}")
        n["dsa_keygen"] += len(rows)
        A(f"static const wy_dsa_keygen_t wy_dsa_keygen_{lvl}[] = {{")
        for s, p in rows:
            A(f'    {{ {cstr(s)}, {cstr(p)} }},')
        A("};")
        A(f"static const size_t wy_dsa_keygen_{lvl}_n = {len(rows)};")
        A("")
        # verify: every 7th valid + every 3rd same-shape invalid, good pk.
        # Context-carrying vectors (tcId 3,4,5 per level) are handled
        # explicitly: valid with ctx<=255 -> expect OK under that ctx;
        # "context too long" (256) -> expect BAD_LENGTH (adapter gate);
        # 256-byte encoder edge cases (tcId 140-143) skipped — same gate
        # path as "too long" (no new behavior), encoder intent belongs to
        # backend review. Wrong-shape vectors counted, not silently dropped.
        d = load(indir, f"mldsa_{lvl}_verify_test.json")
        ok_all, bad_all, ctx_rows = [], [], []
        skipped_grp, skipped_sig, skipped_enc = 0, 0, 0
        for g in d["testGroups"]:
            if not g.get("publicKey") or len(g["publicKey"]) // 2 != pk:
                skipped_grp += len(g["tests"])
                continue
            for t in g["tests"]:
                if len(t.get("sig", "")) // 2 != sig:
                    skipped_sig += 1
                    continue
                ctx = t.get("ctx", "")
                if ctx:
                    assert len(ctx) % 2 == 0
                    if t.get("result") == "valid" and len(ctx) // 2 <= 255:
                        ctx_rows.append((hx(g["publicKey"]),
                                         hx(t.get("msg", "")), hx(t["sig"]),
                                         hx(ctx), 0))
                    elif t.get("comment") == "context too long":
                        ctx_rows.append((hx(g["publicKey"]),
                                         hx(t.get("msg", "")), hx(t["sig"]),
                                         hx(ctx), 2))
                    else:
                        skipped_enc += 1
                    continue
                # expect codes: 0 = QC_DSA_OK, 4 = QC_DSA_BAD_SIG.
                (ok_all if t.get("result") == "valid" else bad_all).append(
                    (hx(g["publicKey"]), hx(t.get("msg", "")), hx(t["sig"]),
                     0 if t.get("result") == "valid" else 4))
        print(f"dsa{lvl} verify skipped: badpk-group={skipped_grp} "
              f"badsiglen={skipped_sig} encoder-edge={skipped_enc}")
        ok_sel = [r for i, r in enumerate(ok_all) if i % STRIDE_VALID == 0]
        bad_sel = [r for i, r in enumerate(bad_all) if i % STRIDE_INVALID == 0]
        all_rows = ok_sel + bad_sel + ctx_rows
        n["dsa_verify"] += len(all_rows)
        A(f"static const wy_dsa_verify_t wy_dsa_verify_{lvl}[] = {{")
        for p, m, s, e in ok_sel + bad_sel:
            A(f'    {{ {cstr(p)}, {cstr(m)}, {cstr(s)}, "", {e} }},')
        for p, m, s, c, e in ctx_rows:
            A(f'    {{ {cstr(p)}, {cstr(m)}, {cstr(s)}, {cstr(c)}, {e} }},')
        A("};")
        A(f"static const size_t wy_dsa_verify_{lvl}_n = {len(all_rows)};")
        A("")

    A("#endif")
    # UTF-8 explicitly: Windows Python defaults to cp1252, which would
    # corrupt any non-ASCII byte in a generated C source file.
    open(outpath, "w", encoding="utf-8").write("\n".join(L))
    print("wrote", outpath, n)


if __name__ == "__main__":
    main()